"""empty message

Revision ID: 186a13e2ca82
Revises: 2d6f05a6f9c9
Create Date: 2015-06-04 21:02:09.968940

"""

# revision identifiers, used by Alembic.
revision = '186a13e2ca82'
down_revision = '2d6f05a6f9c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sensors',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('sump_temp', sa.Float(), nullable=True),
        sa.Column('air_temp', sa.Float(), nullable=True),
        sa.Column('date', sa.DateTime, nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
