"""empty message

Revision ID: 1bf9dc95f05d
Revises: None
Create Date: 2015-06-21 13:42:39.830545

"""

# revision identifiers, used by Alembic.
revision = '1bf9dc95f05d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    	'sensors',
    	sa.Column('pkS', sa.Integer, primary_key=True),
    	sa.Column('sump_temp', sa.Float),
    	sa.Column('air_temp', sa.Float),
    	sa.Column('date', sa.DateTime),
    )

    op.create_table(
    	'switches',
    	sa.Column('pkSw', sa.Integer, primary_key=True),
    	sa.Column('waterSw', sa.Boolean),
    	sa.Column('airSw', sa.Boolean),
    	sa.Column('lightSw', sa.Boolean),
    	sa.Column('dateSw', sa.DateTime),
    )
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    op.drop_table('switches')
    pass
    ### end Alembic commands ###
