"""empty message

Revision ID: 24e41988114c
Revises: None
Create Date: 2015-06-15 22:41:45.929799

"""

# revision identifiers, used by Alembic.
revision = '24e41988114c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
