"""empty message

Revision ID: 2d6f05a6f9c9
Revises: 4558aaecbd92
Create Date: 2015-06-04 20:52:18.493968

"""

# revision identifiers, used by Alembic.
revision = '2d6f05a6f9c9'
down_revision = '4558aaecbd92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
