"""empty message

Revision ID: 2ec94d28b44b
Revises: None
Create Date: 2015-06-03 22:18:25.254640

"""

# revision identifiers, used by Alembic.
revision = '2ec94d28b44b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
