"""empty message

Revision ID: 35b2c3ccbb17
Revises: 1bf9dc95f05d
Create Date: 2015-07-17 16:09:17.443930

"""

# revision identifiers, used by Alembic.
revision = '35b2c3ccbb17'
down_revision = '1bf9dc95f05d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('light_lux', sa.FLOAT(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('pkS', sa.INTEGER(), nullable=False),
    sa.Column('sump_temp', sa.FLOAT(), nullable=True),
    sa.Column('air_temp', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('pkS')
    )
    op.create_table('switches',
    sa.Column('pkSw', sa.INTEGER(), nullable=False),
    sa.Column('waterSw', sa.BOOLEAN(), nullable=True),
    sa.Column('airSw', sa.BOOLEAN(), nullable=True),
    sa.Column('lightSw', sa.BOOLEAN(), nullable=True),
    sa.Column('dateSw', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('pkSw')
    )
    ### end Alembic commands ###
