"""empty message

Revision ID: 4ba850632cbd
Revises: 24e41988114c
Create Date: 2015-06-15 22:43:47.358053

"""

# revision identifiers, used by Alembic.
revision = '4ba850632cbd'
down_revision = '24e41988114c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
