"""empty message

Revision ID: 527e6dfb7259
Revises: 59bce613a4f6
Create Date: 2015-06-04 20:33:10.911961

"""

# revision identifiers, used by Alembic.
revision = '527e6dfb7259'
down_revision = '59bce613a4f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sump_temp', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
