"""empty message

Revision ID: 59bce613a4f6
Revises: 2ec94d28b44b
Create Date: 2015-06-04 20:13:47.010773

"""

# revision identifiers, used by Alembic.
revision = '59bce613a4f6'
down_revision = '2ec94d28b44b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
